services:
  iris:
    init: true
    container_name: iris
    build: 
      context: .
      dockerfile: iris/Dockerfile
    command: --check-caps false
    ports:
      - "1972:1972"
      - "52773:52773"
      - "53773:53773"
    volumes:
      - ./:/irisrun/repo
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
   
   # angular
  angular:
    init: true
    container_name: ui
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - iris